name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.5
  file_picker: ^8.1.4
  flutter_form_builder: ^9.5.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.8
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/